//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.23 at 01:05:37 PM JST 
//


package com.change_vision.astah.extension.plugin.doxygen._1_8_4.index;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompoundKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CompoundKind">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="class"/>
 *     &lt;enumeration value="struct"/>
 *     &lt;enumeration value="union"/>
 *     &lt;enumeration value="interface"/>
 *     &lt;enumeration value="protocol"/>
 *     &lt;enumeration value="category"/>
 *     &lt;enumeration value="exception"/>
 *     &lt;enumeration value="file"/>
 *     &lt;enumeration value="namespace"/>
 *     &lt;enumeration value="group"/>
 *     &lt;enumeration value="page"/>
 *     &lt;enumeration value="example"/>
 *     &lt;enumeration value="dir"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CompoundKind")
@XmlEnum
public enum CompoundKind {

    @XmlEnumValue("class")
    CLASS("class"),
    @XmlEnumValue("struct")
    STRUCT("struct"),
    @XmlEnumValue("union")
    UNION("union"),
    @XmlEnumValue("interface")
    INTERFACE("interface"),
    @XmlEnumValue("protocol")
    PROTOCOL("protocol"),
    @XmlEnumValue("category")
    CATEGORY("category"),
    @XmlEnumValue("exception")
    EXCEPTION("exception"),
    @XmlEnumValue("file")
    FILE("file"),
    @XmlEnumValue("namespace")
    NAMESPACE("namespace"),
    @XmlEnumValue("group")
    GROUP("group"),
    @XmlEnumValue("page")
    PAGE("page"),
    @XmlEnumValue("example")
    EXAMPLE("example"),
    @XmlEnumValue("dir")
    DIR("dir");
    private final String value;

    CompoundKind(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CompoundKind fromValue(String v) {
        for (CompoundKind c: CompoundKind.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
