//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.23 at 01:05:37 PM JST 
//


package com.change_vision.astah.extension.plugin.doxygen._1_8_4.index;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.change_vision.astah.extension.plugin.doxygen._1_8_4.index package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Doxygenindex_QNAME = new QName("", "doxygenindex");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.change_vision.astah.extension.plugin.doxygen._1_8_4.index
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DoxygenType }
     * 
     */
    public DoxygenType createDoxygenType() {
        return new DoxygenType();
    }

    /**
     * Create an instance of {@link MemberType }
     * 
     */
    public MemberType createMemberType() {
        return new MemberType();
    }

    /**
     * Create an instance of {@link CompoundType }
     * 
     */
    public CompoundType createCompoundType() {
        return new CompoundType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DoxygenType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "doxygenindex")
    public JAXBElement<DoxygenType> createDoxygenindex(DoxygenType value) {
        return new JAXBElement<DoxygenType>(_Doxygenindex_QNAME, DoxygenType.class, null, value);
    }

}
