//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.23 at 01:05:21 PM JST 
//


package com.change_vision.astah.extension.plugin.doxygen._1_8_4.compound;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DoxParamListKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DoxParamListKind">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="param"/>
 *     &lt;enumeration value="retval"/>
 *     &lt;enumeration value="exception"/>
 *     &lt;enumeration value="templateparam"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DoxParamListKind")
@XmlEnum
public enum DoxParamListKind {

    @XmlEnumValue("param")
    PARAM("param"),
    @XmlEnumValue("retval")
    RETVAL("retval"),
    @XmlEnumValue("exception")
    EXCEPTION("exception"),
    @XmlEnumValue("templateparam")
    TEMPLATEPARAM("templateparam");
    private final String value;

    DoxParamListKind(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DoxParamListKind fromValue(String v) {
        for (DoxParamListKind c: DoxParamListKind.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
