//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.23 at 01:05:21 PM JST 
//


package com.change_vision.astah.extension.plugin.doxygen._1_8_4.compound;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for memberRefType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="memberRefType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scope" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="refid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="prot" type="{}DoxProtectionKind" />
 *       &lt;attribute name="virt" type="{}DoxVirtualKind" />
 *       &lt;attribute name="ambiguityscope" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "memberRefType", propOrder = {
    "scope",
    "name"
})
public class MemberRefType {

    @XmlElement(required = true)
    protected Object scope;
    @XmlElement(required = true)
    protected Object name;
    @XmlAttribute(name = "refid")
    protected String refid;
    @XmlAttribute(name = "prot")
    protected DoxProtectionKind prot;
    @XmlAttribute(name = "virt")
    protected DoxVirtualKind virt;
    @XmlAttribute(name = "ambiguityscope")
    protected String ambiguityscope;

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getScope() {
        return scope;
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setScope(Object value) {
        this.scope = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setName(Object value) {
        this.name = value;
    }

    /**
     * Gets the value of the refid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefid() {
        return refid;
    }

    /**
     * Sets the value of the refid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefid(String value) {
        this.refid = value;
    }

    /**
     * Gets the value of the prot property.
     * 
     * @return
     *     possible object is
     *     {@link DoxProtectionKind }
     *     
     */
    public DoxProtectionKind getProt() {
        return prot;
    }

    /**
     * Sets the value of the prot property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxProtectionKind }
     *     
     */
    public void setProt(DoxProtectionKind value) {
        this.prot = value;
    }

    /**
     * Gets the value of the virt property.
     * 
     * @return
     *     possible object is
     *     {@link DoxVirtualKind }
     *     
     */
    public DoxVirtualKind getVirt() {
        return virt;
    }

    /**
     * Sets the value of the virt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxVirtualKind }
     *     
     */
    public void setVirt(DoxVirtualKind value) {
        this.virt = value;
    }

    /**
     * Gets the value of the ambiguityscope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmbiguityscope() {
        return ambiguityscope;
    }

    /**
     * Sets the value of the ambiguityscope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmbiguityscope(String value) {
        this.ambiguityscope = value;
    }

}
