//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.22 at 11:08:54 AM JST 
//


package com.change_vision.astah.extension.plugin.doxygen._1_8_3_1.compound;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for docParamListItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="docParamListItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parameternamelist" type="{}docParamNameList" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="parameterdescription" type="{}descriptionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "docParamListItem", propOrder = {
    "parameternamelist",
    "parameterdescription"
})
public class DocParamListItem {

    protected List<DocParamNameList> parameternamelist;
    @XmlElement(required = true)
    protected DescriptionType parameterdescription;

    /**
     * Gets the value of the parameternamelist property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameternamelist property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameternamelist().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocParamNameList }
     * 
     * 
     */
    public List<DocParamNameList> getParameternamelist() {
        if (parameternamelist == null) {
            parameternamelist = new ArrayList<DocParamNameList>();
        }
        return this.parameternamelist;
    }

    /**
     * Gets the value of the parameterdescription property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptionType }
     *     
     */
    public DescriptionType getParameterdescription() {
        return parameterdescription;
    }

    /**
     * Sets the value of the parameterdescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptionType }
     *     
     */
    public void setParameterdescription(DescriptionType value) {
        this.parameterdescription = value;
    }

}
