//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.22 at 11:08:54 AM JST 
//


package com.change_vision.astah.extension.plugin.doxygen._1_8_3_1.compound;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for docSimpleSectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="docSimpleSectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{}docTitleType" minOccurs="0"/>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="para" type="{}docParaType" maxOccurs="unbounded"/>
 *           &lt;element name="simplesectsep" type="{}docEmptyType" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="kind" type="{}DoxSimpleSectKind" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "docSimpleSectType", propOrder = {
    "title",
    "paraAndSimplesectsep"
})
public class DocSimpleSectType {

    protected DocTitleType title;
    @XmlElements({
        @XmlElement(name = "para", type = DocParaType.class),
        @XmlElement(name = "simplesectsep", type = DocEmptyType.class)
    })
    protected List<Object> paraAndSimplesectsep;
    @XmlAttribute(name = "kind")
    protected DoxSimpleSectKind kind;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link DocTitleType }
     *     
     */
    public DocTitleType getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocTitleType }
     *     
     */
    public void setTitle(DocTitleType value) {
        this.title = value;
    }

    /**
     * Gets the value of the paraAndSimplesectsep property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paraAndSimplesectsep property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParaAndSimplesectsep().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocParaType }
     * {@link DocEmptyType }
     * 
     * 
     */
    public List<Object> getParaAndSimplesectsep() {
        if (paraAndSimplesectsep == null) {
            paraAndSimplesectsep = new ArrayList<Object>();
        }
        return this.paraAndSimplesectsep;
    }

    /**
     * Gets the value of the kind property.
     * 
     * @return
     *     possible object is
     *     {@link DoxSimpleSectKind }
     *     
     */
    public DoxSimpleSectKind getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxSimpleSectKind }
     *     
     */
    public void setKind(DoxSimpleSectKind value) {
        this.kind = value;
    }

}
