//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.22 at 11:08:54 AM JST 
//


package com.change_vision.astah.extension.plugin.doxygen._1_8_3_1.compound;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DoxProtectionKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DoxProtectionKind">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="public"/>
 *     &lt;enumeration value="protected"/>
 *     &lt;enumeration value="private"/>
 *     &lt;enumeration value="package"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DoxProtectionKind")
@XmlEnum
public enum DoxProtectionKind {

    @XmlEnumValue("public")
    PUBLIC("public"),
    @XmlEnumValue("protected")
    PROTECTED("protected"),
    @XmlEnumValue("private")
    PRIVATE("private"),
    @XmlEnumValue("package")
    PACKAGE("package");
    private final String value;

    DoxProtectionKind(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DoxProtectionKind fromValue(String v) {
        for (DoxProtectionKind c: DoxProtectionKind.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
