//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.22 at 11:08:54 AM JST 
//


package com.change_vision.astah.extension.plugin.doxygen._1_8_3_1.compound;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for memberdefType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="memberdefType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="templateparamlist" type="{}templateparamlistType" minOccurs="0"/>
 *         &lt;element name="type" type="{}linkedTextType" minOccurs="0"/>
 *         &lt;element name="definition" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="argsstring" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="read" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="write" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="bitfield" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="reimplements" type="{}reimplementType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reimplementedby" type="{}reimplementType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="param" type="{}paramType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="enumvalue" type="{}enumvalueType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="initializer" type="{}linkedTextType" minOccurs="0"/>
 *         &lt;element name="exceptions" type="{}linkedTextType" minOccurs="0"/>
 *         &lt;element name="briefdescription" type="{}descriptionType" minOccurs="0"/>
 *         &lt;element name="detaileddescription" type="{}descriptionType" minOccurs="0"/>
 *         &lt;element name="inbodydescription" type="{}descriptionType" minOccurs="0"/>
 *         &lt;element name="location" type="{}locationType"/>
 *         &lt;element name="references" type="{}referenceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="referencedby" type="{}referenceType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="kind" type="{}DoxMemberKind" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="prot" type="{}DoxProtectionKind" />
 *       &lt;attribute name="static" type="{}DoxBool" />
 *       &lt;attribute name="const" type="{}DoxBool" />
 *       &lt;attribute name="explicit" type="{}DoxBool" />
 *       &lt;attribute name="inline" type="{}DoxBool" />
 *       &lt;attribute name="virt" type="{}DoxVirtualKind" />
 *       &lt;attribute name="volatile" type="{}DoxBool" />
 *       &lt;attribute name="mutable" type="{}DoxBool" />
 *       &lt;attribute name="readable" type="{}DoxBool" />
 *       &lt;attribute name="writable" type="{}DoxBool" />
 *       &lt;attribute name="initonly" type="{}DoxBool" />
 *       &lt;attribute name="settable" type="{}DoxBool" />
 *       &lt;attribute name="gettable" type="{}DoxBool" />
 *       &lt;attribute name="final" type="{}DoxBool" />
 *       &lt;attribute name="sealed" type="{}DoxBool" />
 *       &lt;attribute name="new" type="{}DoxBool" />
 *       &lt;attribute name="add" type="{}DoxBool" />
 *       &lt;attribute name="remove" type="{}DoxBool" />
 *       &lt;attribute name="raise" type="{}DoxBool" />
 *       &lt;attribute name="optional" type="{}DoxBool" />
 *       &lt;attribute name="required" type="{}DoxBool" />
 *       &lt;attribute name="accessor" type="{}DoxAccessor" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "memberdefType", propOrder = {
    "templateparamlist",
    "type",
    "definition",
    "argsstring",
    "name",
    "read",
    "write",
    "bitfield",
    "reimplements",
    "reimplementedby",
    "param",
    "enumvalue",
    "initializer",
    "exceptions",
    "briefdescription",
    "detaileddescription",
    "inbodydescription",
    "location",
    "references",
    "referencedby"
})
public class MemberdefType {

    protected TemplateparamlistType templateparamlist;
    protected LinkedTextType type;
    protected Object definition;
    protected Object argsstring;
    @XmlElement(required = true)
    protected Object name;
    protected Object read;
    protected Object write;
    protected Object bitfield;
    protected List<ReimplementType> reimplements;
    protected List<ReimplementType> reimplementedby;
    protected List<ParamType> param;
    protected List<EnumvalueType> enumvalue;
    protected LinkedTextType initializer;
    protected LinkedTextType exceptions;
    protected DescriptionType briefdescription;
    protected DescriptionType detaileddescription;
    protected DescriptionType inbodydescription;
    @XmlElement(required = true)
    protected LocationType location;
    protected List<ReferenceType> references;
    protected List<ReferenceType> referencedby;
    @XmlAttribute(name = "kind")
    protected DoxMemberKind kind;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "prot")
    protected DoxProtectionKind prot;
    @XmlAttribute(name = "static")
    protected DoxBool _static;
    @XmlAttribute(name = "const")
    protected DoxBool _const;
    @XmlAttribute(name = "explicit")
    protected DoxBool explicit;
    @XmlAttribute(name = "inline")
    protected DoxBool inline;
    @XmlAttribute(name = "virt")
    protected DoxVirtualKind virt;
    @XmlAttribute(name = "volatile")
    protected DoxBool _volatile;
    @XmlAttribute(name = "mutable")
    protected DoxBool mutable;
    @XmlAttribute(name = "readable")
    protected DoxBool readable;
    @XmlAttribute(name = "writable")
    protected DoxBool writable;
    @XmlAttribute(name = "initonly")
    protected DoxBool initonly;
    @XmlAttribute(name = "settable")
    protected DoxBool settable;
    @XmlAttribute(name = "gettable")
    protected DoxBool gettable;
    @XmlAttribute(name = "final")
    protected DoxBool _final;
    @XmlAttribute(name = "sealed")
    protected DoxBool sealed;
    @XmlAttribute(name = "new")
    protected DoxBool _new;
    @XmlAttribute(name = "add")
    protected DoxBool add;
    @XmlAttribute(name = "remove")
    protected DoxBool remove;
    @XmlAttribute(name = "raise")
    protected DoxBool raise;
    @XmlAttribute(name = "optional")
    protected DoxBool optional;
    @XmlAttribute(name = "required")
    protected DoxBool required;
    @XmlAttribute(name = "accessor")
    protected DoxAccessor accessor;

    /**
     * Gets the value of the templateparamlist property.
     * 
     * @return
     *     possible object is
     *     {@link TemplateparamlistType }
     *     
     */
    public TemplateparamlistType getTemplateparamlist() {
        return templateparamlist;
    }

    /**
     * Sets the value of the templateparamlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemplateparamlistType }
     *     
     */
    public void setTemplateparamlist(TemplateparamlistType value) {
        this.templateparamlist = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link LinkedTextType }
     *     
     */
    public LinkedTextType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkedTextType }
     *     
     */
    public void setType(LinkedTextType value) {
        this.type = value;
    }

    /**
     * Gets the value of the definition property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDefinition() {
        return definition;
    }

    /**
     * Sets the value of the definition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDefinition(Object value) {
        this.definition = value;
    }

    /**
     * Gets the value of the argsstring property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getArgsstring() {
        return argsstring;
    }

    /**
     * Sets the value of the argsstring property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setArgsstring(Object value) {
        this.argsstring = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setName(Object value) {
        this.name = value;
    }

    /**
     * Gets the value of the read property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getRead() {
        return read;
    }

    /**
     * Sets the value of the read property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setRead(Object value) {
        this.read = value;
    }

    /**
     * Gets the value of the write property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getWrite() {
        return write;
    }

    /**
     * Sets the value of the write property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setWrite(Object value) {
        this.write = value;
    }

    /**
     * Gets the value of the bitfield property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getBitfield() {
        return bitfield;
    }

    /**
     * Sets the value of the bitfield property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setBitfield(Object value) {
        this.bitfield = value;
    }

    /**
     * Gets the value of the reimplements property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reimplements property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReimplements().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReimplementType }
     * 
     * 
     */
    public List<ReimplementType> getReimplements() {
        if (reimplements == null) {
            reimplements = new ArrayList<ReimplementType>();
        }
        return this.reimplements;
    }

    /**
     * Gets the value of the reimplementedby property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reimplementedby property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReimplementedby().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReimplementType }
     * 
     * 
     */
    public List<ReimplementType> getReimplementedby() {
        if (reimplementedby == null) {
            reimplementedby = new ArrayList<ReimplementType>();
        }
        return this.reimplementedby;
    }

    /**
     * Gets the value of the param property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the param property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamType }
     * 
     * 
     */
    public List<ParamType> getParam() {
        if (param == null) {
            param = new ArrayList<ParamType>();
        }
        return this.param;
    }

    /**
     * Gets the value of the enumvalue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the enumvalue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnumvalue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnumvalueType }
     * 
     * 
     */
    public List<EnumvalueType> getEnumvalue() {
        if (enumvalue == null) {
            enumvalue = new ArrayList<EnumvalueType>();
        }
        return this.enumvalue;
    }

    /**
     * Gets the value of the initializer property.
     * 
     * @return
     *     possible object is
     *     {@link LinkedTextType }
     *     
     */
    public LinkedTextType getInitializer() {
        return initializer;
    }

    /**
     * Sets the value of the initializer property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkedTextType }
     *     
     */
    public void setInitializer(LinkedTextType value) {
        this.initializer = value;
    }

    /**
     * Gets the value of the exceptions property.
     * 
     * @return
     *     possible object is
     *     {@link LinkedTextType }
     *     
     */
    public LinkedTextType getExceptions() {
        return exceptions;
    }

    /**
     * Sets the value of the exceptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkedTextType }
     *     
     */
    public void setExceptions(LinkedTextType value) {
        this.exceptions = value;
    }

    /**
     * Gets the value of the briefdescription property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptionType }
     *     
     */
    public DescriptionType getBriefdescription() {
        return briefdescription;
    }

    /**
     * Sets the value of the briefdescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptionType }
     *     
     */
    public void setBriefdescription(DescriptionType value) {
        this.briefdescription = value;
    }

    /**
     * Gets the value of the detaileddescription property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptionType }
     *     
     */
    public DescriptionType getDetaileddescription() {
        return detaileddescription;
    }

    /**
     * Sets the value of the detaileddescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptionType }
     *     
     */
    public void setDetaileddescription(DescriptionType value) {
        this.detaileddescription = value;
    }

    /**
     * Gets the value of the inbodydescription property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptionType }
     *     
     */
    public DescriptionType getInbodydescription() {
        return inbodydescription;
    }

    /**
     * Sets the value of the inbodydescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptionType }
     *     
     */
    public void setInbodydescription(DescriptionType value) {
        this.inbodydescription = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link LocationType }
     *     
     */
    public LocationType getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationType }
     *     
     */
    public void setLocation(LocationType value) {
        this.location = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the references property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferences().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReferenceType }
     * 
     * 
     */
    public List<ReferenceType> getReferences() {
        if (references == null) {
            references = new ArrayList<ReferenceType>();
        }
        return this.references;
    }

    /**
     * Gets the value of the referencedby property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the referencedby property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReferencedby().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReferenceType }
     * 
     * 
     */
    public List<ReferenceType> getReferencedby() {
        if (referencedby == null) {
            referencedby = new ArrayList<ReferenceType>();
        }
        return this.referencedby;
    }

    /**
     * Gets the value of the kind property.
     * 
     * @return
     *     possible object is
     *     {@link DoxMemberKind }
     *     
     */
    public DoxMemberKind getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxMemberKind }
     *     
     */
    public void setKind(DoxMemberKind value) {
        this.kind = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the prot property.
     * 
     * @return
     *     possible object is
     *     {@link DoxProtectionKind }
     *     
     */
    public DoxProtectionKind getProt() {
        return prot;
    }

    /**
     * Sets the value of the prot property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxProtectionKind }
     *     
     */
    public void setProt(DoxProtectionKind value) {
        this.prot = value;
    }

    /**
     * Gets the value of the static property.
     * 
     * @return
     *     possible object is
     *     {@link DoxBool }
     *     
     */
    public DoxBool getStatic() {
        return _static;
    }

    /**
     * Sets the value of the static property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxBool }
     *     
     */
    public void setStatic(DoxBool value) {
        this._static = value;
    }

    /**
     * Gets the value of the const property.
     * 
     * @return
     *     possible object is
     *     {@link DoxBool }
     *     
     */
    public DoxBool getConst() {
        return _const;
    }

    /**
     * Sets the value of the const property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxBool }
     *     
     */
    public void setConst(DoxBool value) {
        this._const = value;
    }

    /**
     * Gets the value of the explicit property.
     * 
     * @return
     *     possible object is
     *     {@link DoxBool }
     *     
     */
    public DoxBool getExplicit() {
        return explicit;
    }

    /**
     * Sets the value of the explicit property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxBool }
     *     
     */
    public void setExplicit(DoxBool value) {
        this.explicit = value;
    }

    /**
     * Gets the value of the inline property.
     * 
     * @return
     *     possible object is
     *     {@link DoxBool }
     *     
     */
    public DoxBool getInline() {
        return inline;
    }

    /**
     * Sets the value of the inline property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxBool }
     *     
     */
    public void setInline(DoxBool value) {
        this.inline = value;
    }

    /**
     * Gets the value of the virt property.
     * 
     * @return
     *     possible object is
     *     {@link DoxVirtualKind }
     *     
     */
    public DoxVirtualKind getVirt() {
        return virt;
    }

    /**
     * Sets the value of the virt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxVirtualKind }
     *     
     */
    public void setVirt(DoxVirtualKind value) {
        this.virt = value;
    }

    /**
     * Gets the value of the volatile property.
     * 
     * @return
     *     possible object is
     *     {@link DoxBool }
     *     
     */
    public DoxBool getVolatile() {
        return _volatile;
    }

    /**
     * Sets the value of the volatile property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxBool }
     *     
     */
    public void setVolatile(DoxBool value) {
        this._volatile = value;
    }

    /**
     * Gets the value of the mutable property.
     * 
     * @return
     *     possible object is
     *     {@link DoxBool }
     *     
     */
    public DoxBool getMutable() {
        return mutable;
    }

    /**
     * Sets the value of the mutable property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxBool }
     *     
     */
    public void setMutable(DoxBool value) {
        this.mutable = value;
    }

    /**
     * Gets the value of the readable property.
     * 
     * @return
     *     possible object is
     *     {@link DoxBool }
     *     
     */
    public DoxBool getReadable() {
        return readable;
    }

    /**
     * Sets the value of the readable property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxBool }
     *     
     */
    public void setReadable(DoxBool value) {
        this.readable = value;
    }

    /**
     * Gets the value of the writable property.
     * 
     * @return
     *     possible object is
     *     {@link DoxBool }
     *     
     */
    public DoxBool getWritable() {
        return writable;
    }

    /**
     * Sets the value of the writable property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxBool }
     *     
     */
    public void setWritable(DoxBool value) {
        this.writable = value;
    }

    /**
     * Gets the value of the initonly property.
     * 
     * @return
     *     possible object is
     *     {@link DoxBool }
     *     
     */
    public DoxBool getInitonly() {
        return initonly;
    }

    /**
     * Sets the value of the initonly property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxBool }
     *     
     */
    public void setInitonly(DoxBool value) {
        this.initonly = value;
    }

    /**
     * Gets the value of the settable property.
     * 
     * @return
     *     possible object is
     *     {@link DoxBool }
     *     
     */
    public DoxBool getSettable() {
        return settable;
    }

    /**
     * Sets the value of the settable property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxBool }
     *     
     */
    public void setSettable(DoxBool value) {
        this.settable = value;
    }

    /**
     * Gets the value of the gettable property.
     * 
     * @return
     *     possible object is
     *     {@link DoxBool }
     *     
     */
    public DoxBool getGettable() {
        return gettable;
    }

    /**
     * Sets the value of the gettable property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxBool }
     *     
     */
    public void setGettable(DoxBool value) {
        this.gettable = value;
    }

    /**
     * Gets the value of the final property.
     * 
     * @return
     *     possible object is
     *     {@link DoxBool }
     *     
     */
    public DoxBool getFinal() {
        return _final;
    }

    /**
     * Sets the value of the final property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxBool }
     *     
     */
    public void setFinal(DoxBool value) {
        this._final = value;
    }

    /**
     * Gets the value of the sealed property.
     * 
     * @return
     *     possible object is
     *     {@link DoxBool }
     *     
     */
    public DoxBool getSealed() {
        return sealed;
    }

    /**
     * Sets the value of the sealed property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxBool }
     *     
     */
    public void setSealed(DoxBool value) {
        this.sealed = value;
    }

    /**
     * Gets the value of the new property.
     * 
     * @return
     *     possible object is
     *     {@link DoxBool }
     *     
     */
    public DoxBool getNew() {
        return _new;
    }

    /**
     * Sets the value of the new property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxBool }
     *     
     */
    public void setNew(DoxBool value) {
        this._new = value;
    }

    /**
     * Gets the value of the add property.
     * 
     * @return
     *     possible object is
     *     {@link DoxBool }
     *     
     */
    public DoxBool getAdd() {
        return add;
    }

    /**
     * Sets the value of the add property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxBool }
     *     
     */
    public void setAdd(DoxBool value) {
        this.add = value;
    }

    /**
     * Gets the value of the remove property.
     * 
     * @return
     *     possible object is
     *     {@link DoxBool }
     *     
     */
    public DoxBool getRemove() {
        return remove;
    }

    /**
     * Sets the value of the remove property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxBool }
     *     
     */
    public void setRemove(DoxBool value) {
        this.remove = value;
    }

    /**
     * Gets the value of the raise property.
     * 
     * @return
     *     possible object is
     *     {@link DoxBool }
     *     
     */
    public DoxBool getRaise() {
        return raise;
    }

    /**
     * Sets the value of the raise property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxBool }
     *     
     */
    public void setRaise(DoxBool value) {
        this.raise = value;
    }

    /**
     * Gets the value of the optional property.
     * 
     * @return
     *     possible object is
     *     {@link DoxBool }
     *     
     */
    public DoxBool getOptional() {
        return optional;
    }

    /**
     * Sets the value of the optional property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxBool }
     *     
     */
    public void setOptional(DoxBool value) {
        this.optional = value;
    }

    /**
     * Gets the value of the required property.
     * 
     * @return
     *     possible object is
     *     {@link DoxBool }
     *     
     */
    public DoxBool getRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxBool }
     *     
     */
    public void setRequired(DoxBool value) {
        this.required = value;
    }

    /**
     * Gets the value of the accessor property.
     * 
     * @return
     *     possible object is
     *     {@link DoxAccessor }
     *     
     */
    public DoxAccessor getAccessor() {
        return accessor;
    }

    /**
     * Sets the value of the accessor property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoxAccessor }
     *     
     */
    public void setAccessor(DoxAccessor value) {
        this.accessor = value;
    }

}
