//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.22 at 11:08:54 AM JST 
//


package com.change_vision.astah.extension.plugin.doxygen._1_8_3_1.compound;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for paramType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="paramType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{}linkedTextType" minOccurs="0"/>
 *         &lt;element name="declname" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="defname" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="array" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="defval" type="{}linkedTextType" minOccurs="0"/>
 *         &lt;element name="briefdescription" type="{}descriptionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paramType", propOrder = {
    "type",
    "declname",
    "defname",
    "array",
    "defval",
    "briefdescription"
})
public class ParamType {

    protected LinkedTextType type;
    protected Object declname;
    protected Object defname;
    protected Object array;
    protected LinkedTextType defval;
    protected DescriptionType briefdescription;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link LinkedTextType }
     *     
     */
    public LinkedTextType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkedTextType }
     *     
     */
    public void setType(LinkedTextType value) {
        this.type = value;
    }

    /**
     * Gets the value of the declname property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDeclname() {
        return declname;
    }

    /**
     * Sets the value of the declname property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDeclname(Object value) {
        this.declname = value;
    }

    /**
     * Gets the value of the defname property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDefname() {
        return defname;
    }

    /**
     * Sets the value of the defname property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDefname(Object value) {
        this.defname = value;
    }

    /**
     * Gets the value of the array property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getArray() {
        return array;
    }

    /**
     * Sets the value of the array property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setArray(Object value) {
        this.array = value;
    }

    /**
     * Gets the value of the defval property.
     * 
     * @return
     *     possible object is
     *     {@link LinkedTextType }
     *     
     */
    public LinkedTextType getDefval() {
        return defval;
    }

    /**
     * Sets the value of the defval property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkedTextType }
     *     
     */
    public void setDefval(LinkedTextType value) {
        this.defval = value;
    }

    /**
     * Gets the value of the briefdescription property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptionType }
     *     
     */
    public DescriptionType getBriefdescription() {
        return briefdescription;
    }

    /**
     * Sets the value of the briefdescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptionType }
     *     
     */
    public void setBriefdescription(DescriptionType value) {
        this.briefdescription = value;
    }

}
